Fix type error on getting source path
It should use `.parent` instead of `.parents`.

>   File "setup.py", line 39, in <module>
>     SOURCE = (Path(__file__).parents / "pyvoicechanger.py").read_text()
> TypeError: unsupported operand type(s) for /: '_PathParents' and 'str'